# Site settings
title: Xiao‘Blog
email: i.yxl@foxmail.com
description: "hello world!......."
baseurl: 
url: "http://ixiao.pw"
twitter_username: iyanxiao
github_username:  ixiao
facebook_username:  闫潇

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: 小潇
qq: 592314686
duoshuo: ixiao
weibo: 505501200
github: ixiao
pygments: true
safe: true
paginate: 20
aboutme: "iOS开发，目前正在学习中。	
热爱apple，喜欢互联网，喜欢数码产品，github等。		
古城西安人  	
偶尔微博，偶尔LOL。"
